language: node_js

node_js:
  - "node"

# Enable Greenkeeper's support for npm 5+ lockfiles: https://github.com/greenkeeperio/greenkeeper-lockfile
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: etc/update-lockfile.sh
after_script: etc/push-lockfile.sh
