name: PR tests
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.CLOUDCA_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test
